### ISSUE TITLE
Typos discovered by codespell

### ISSUE THREAD

**Issue by cclauss** [khabdrick/Workout-progress-tracker#2]
[`codespell --quiet-level=2`](https://github.com/khabdrick/Workout-progress-tracker/blob/main/.github/workflows/lint_python.yml#L12) discovers two typos...
```
./README.md:3: impoved ==> improved
./templates/navbar.html:36: acount ==> account
```
https://github.com/khabdrick/Workout-progress-tracker/runs/2051397546#step:7:7

Once these typos have been fixed, the `|| true` should be removed from lines 12 and 15 of
`.github/workflows/lint_python.yml` to make these steps mandatory in future code changes.

**Comment by khabdrick** [comment]
I have made the updates, thanks
